// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (name, is_custom, user_id)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, is_custom, user_id
`

type CreateExerciseParams struct {
	Name     string
	IsCustom bool
	UserID   uuid.NullUUID
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.Name, arg.IsCustom, arg.UserID)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsCustom,
		&i.UserID,
	)
	return i, err
}

const getAllExercisesUserId = `-- name: GetAllExercisesUserId :many
SELECT id, name, is_custom, user_id FROM exercises
WHERE user_id = $1 AND is_custom = true
`

func (q *Queries) GetAllExercisesUserId(ctx context.Context, userID uuid.NullUUID) ([]Exercise, error) {
	rows, err := q.db.QueryContext(ctx, getAllExercisesUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsCustom,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseById = `-- name: GetExerciseById :one
SELECT id, name, is_custom, user_id FROM exercises
WHERE id = $1
`

func (q *Queries) GetExerciseById(ctx context.Context, id uuid.UUID) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, getExerciseById, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsCustom,
		&i.UserID,
	)
	return i, err
}
