// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package database

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (name)
VALUES (
    $1
)
RETURNING id, name
`

func (q *Queries) CreateExercise(ctx context.Context, name string) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, name)
	var i Exercise
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
