// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID   uuid.UUID
	Name string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpireAt  time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
