// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID       uuid.UUID
	Name     string
	IsCustom bool
	UserID   uuid.NullUUID
}

type ProgressionRule struct {
	ID          uuid.UUID
	Label       string
	Rule        string
	Description string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpireAt  time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Username       string
	Email          string
	HashedPassword sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Workout struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	StartedAt time.Time
	EndedAt   time.Time
	Volume    int32
	Prs       int32
}

type WorkoutSet struct {
	ID            uuid.UUID
	WorkoutID     uuid.UUID
	ExerciseID    uuid.UUID
	ProgressTrack uuid.UUID
	WeightInLbs   float64
	Reps          float64
	TimeInSeconds float64
}
