// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progression_rules.sql

package database

import (
	"context"
)

const createProgressionRule = `-- name: CreateProgressionRule :exec
INSERT INTO progression_rules (label, rule, description)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, label, rule, description
`

type CreateProgressionRuleParams struct {
	Label       string
	Rule        string
	Description string
}

func (q *Queries) CreateProgressionRule(ctx context.Context, arg CreateProgressionRuleParams) error {
	_, err := q.db.ExecContext(ctx, createProgressionRule, arg.Label, arg.Rule, arg.Description)
	return err
}

const deleteAllProgressionRules = `-- name: DeleteAllProgressionRules :exec
DELETE FROM progression_rules
`

func (q *Queries) DeleteAllProgressionRules(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllProgressionRules)
	return err
}

const getAllProgressionRules = `-- name: GetAllProgressionRules :many
SELECT id, label, rule, description FROM progression_rules
`

func (q *Queries) GetAllProgressionRules(ctx context.Context) ([]ProgressionRule, error) {
	rows, err := q.db.QueryContext(ctx, getAllProgressionRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProgressionRule
	for rows.Next() {
		var i ProgressionRule
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Rule,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
