// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPrOneRepMaxByExerciseIdUserId = `-- name: GetPrOneRepMaxByExerciseIdUserId :one
SELECT COALESCE(
    ROUND(MAX(workout_sets.weight_in_lbs * (1 + (workout_sets.reps / 30.0))), 2),
    0.0
)::DOUBLE PRECISION as orm
FROM workout_sets 
    INNER JOIN workouts 
        ON workout_sets.workout_id = workouts.id
WHERE workout_sets.exercise_id = $1 
    AND workouts.user_id = $2
`

type GetPrOneRepMaxByExerciseIdUserIdParams struct {
	ExerciseID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) GetPrOneRepMaxByExerciseIdUserId(ctx context.Context, arg GetPrOneRepMaxByExerciseIdUserIdParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPrOneRepMaxByExerciseIdUserId, arg.ExerciseID, arg.UserID)
	var orm float64
	err := row.Scan(&orm)
	return orm, err
}

const getPrVolumeByExerciseIdUserId = `-- name: GetPrVolumeByExerciseIdUserId :one
SELECT COALESCE(
    ROUND(MAX(workout_sets.weight_in_lbs * workout_sets.reps), 2),
    0.0
)::DOUBLE PRECISION as volume
FROM workout_sets 
    INNER JOIN workouts 
        ON workout_sets.workout_id = workouts.id
WHERE workout_sets.exercise_id = $1 
    AND workouts.user_id = $2
`

type GetPrVolumeByExerciseIdUserIdParams struct {
	ExerciseID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) GetPrVolumeByExerciseIdUserId(ctx context.Context, arg GetPrVolumeByExerciseIdUserIdParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getPrVolumeByExerciseIdUserId, arg.ExerciseID, arg.UserID)
	var volume float64
	err := row.Scan(&volume)
	return volume, err
}
