// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (user_id, started_at, ended_at, volume, prs)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, started_at, ended_at, volume, prs
`

type CreateWorkoutParams struct {
	UserID    uuid.UUID
	StartedAt time.Time
	EndedAt   time.Time
	Volume    int32
	Prs       int32
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Volume,
		arg.Prs,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Volume,
		&i.Prs,
	)
	return i, err
}
