// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workouts.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkout = `-- name: CreateWorkout :one
INSERT INTO workouts (user_id, started_at, ended_at, volume, prs)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, started_at, ended_at, volume, prs, is_completed
`

type CreateWorkoutParams struct {
	UserID    uuid.UUID
	StartedAt time.Time
	EndedAt   time.Time
	Volume    int32
	Prs       int32
}

func (q *Queries) CreateWorkout(ctx context.Context, arg CreateWorkoutParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, createWorkout,
		arg.UserID,
		arg.StartedAt,
		arg.EndedAt,
		arg.Volume,
		arg.Prs,
	)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Volume,
		&i.Prs,
		&i.IsCompleted,
	)
	return i, err
}

const deleteWorkoutById = `-- name: DeleteWorkoutById :exec
DELETE FROM workouts
WHERE id = $1
`

func (q *Queries) DeleteWorkoutById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteWorkoutById, id)
	return err
}

const getAllWorkoutsByUserId = `-- name: GetAllWorkoutsByUserId :many
SELECT id, user_id, started_at, ended_at, volume, prs, is_completed FROM workouts
WHERE user_id = $1
`

func (q *Queries) GetAllWorkoutsByUserId(ctx context.Context, userID uuid.UUID) ([]Workout, error) {
	rows, err := q.db.QueryContext(ctx, getAllWorkoutsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workout
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.Volume,
			&i.Prs,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkoutById = `-- name: GetWorkoutById :one
SELECT id, user_id, started_at, ended_at, volume, prs, is_completed FROM workouts
WHERE id = $1
`

func (q *Queries) GetWorkoutById(ctx context.Context, id uuid.UUID) (Workout, error) {
	row := q.db.QueryRowContext(ctx, getWorkoutById, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Volume,
		&i.Prs,
		&i.IsCompleted,
	)
	return i, err
}

const updateWorkoutCompletedById = `-- name: UpdateWorkoutCompletedById :one
UPDATE workouts
SET is_completed = true
WHERE id = $1
RETURNING id, user_id, started_at, ended_at, volume, prs, is_completed
`

func (q *Queries) UpdateWorkoutCompletedById(ctx context.Context, id uuid.UUID) (Workout, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutCompletedById, id)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Volume,
		&i.Prs,
		&i.IsCompleted,
	)
	return i, err
}

const updateWorkoutPrVolumeById = `-- name: UpdateWorkoutPrVolumeById :one
UPDATE workouts
SET volume = $2, prs = $3
WHERE id = $1
RETURNING id, user_id, started_at, ended_at, volume, prs, is_completed
`

type UpdateWorkoutPrVolumeByIdParams struct {
	ID     uuid.UUID
	Volume int32
	Prs    int32
}

func (q *Queries) UpdateWorkoutPrVolumeById(ctx context.Context, arg UpdateWorkoutPrVolumeByIdParams) (Workout, error) {
	row := q.db.QueryRowContext(ctx, updateWorkoutPrVolumeById, arg.ID, arg.Volume, arg.Prs)
	var i Workout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.Volume,
		&i.Prs,
		&i.IsCompleted,
	)
	return i, err
}
