// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workout_sets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createWorkoutSetByWorkoutId = `-- name: CreateWorkoutSetByWorkoutId :one
INSERT INTO workout_sets (workout_id, exercise_id, progress_track, weight_in_lbs, reps, time_in_seconds)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, workout_id, exercise_id, progress_track, weight_in_lbs, reps, time_in_seconds
`

type CreateWorkoutSetByWorkoutIdParams struct {
	WorkoutID     uuid.UUID
	ExerciseID    uuid.UUID
	ProgressTrack uuid.UUID
	WeightInLbs   float64
	Reps          float64
	TimeInSeconds float64
}

func (q *Queries) CreateWorkoutSetByWorkoutId(ctx context.Context, arg CreateWorkoutSetByWorkoutIdParams) (WorkoutSet, error) {
	row := q.db.QueryRowContext(ctx, createWorkoutSetByWorkoutId,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.ProgressTrack,
		arg.WeightInLbs,
		arg.Reps,
		arg.TimeInSeconds,
	)
	var i WorkoutSet
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.ProgressTrack,
		&i.WeightInLbs,
		&i.Reps,
		&i.TimeInSeconds,
	)
	return i, err
}
