@host = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvdmVybG9hZGVkIiwic3ViIjoiMDVjZjYwYzMtYjczMC00ZTQwLWE0OTUtMjMyZDNiNTg3NjM3IiwiZXhwIjoxNzc2ODMyMjA2LCJpYXQiOjE3NzY4Mjg2MDZ9.dvlMviwHIUGQS57NeLRsbvBylLxKKXSRLRkBDSXXx8o
@refresh_token = 7bdb0c7321b519a5d7c0966921223d869e02d425d66bdacafde9296b410f66db
@workout_id = 9d667d95-9c83-4c51-add4-83d0166914ef
@exercise_id_a = "aaa9d580-9cb9-4b82-a43e-999da8f63ada"
@exercise_id_b = "8fb51970-46a9-4fb9-bb95-95571b728a53"
@prog_track = "d5ed01a7-a710-44cc-ad2f-7850d1916fe7"

DELETE {{host}}/admin/reset
###
POST {{host}}/api/users/register
Content-Type: application/json

{
    "email": "gamvred7@gmail.com",
    "username": "gabeamv",
    "password": "password123"
}
###
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username": "gabeamv",
    "password": "password123"
}
###
PUT {{host}}/api/users/username
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "g"
}
###
PUT {{host}}/api/users/email
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "gamvred7@yahoo.com"
}
###
PUT {{host}}/api/users/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "123password"
}
###
POST {{host}}/api/refresh
Content-Type: application/json
Authorization: Bearer {{refresh_token}}
###
POST {{host}}/api/revoke
Content-Type: application/json
Authorization: Bearer {{refresh_token}}
###
POST {{host}}/api/exercises
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "push",
    "is_custom": true
}
###
POST {{host}}/api/exercises
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "pull",
    "is_custom": true
}
###
GET {{host}}/api/exercises
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/api/exercises/7d0b720b-73ab-4a61-b43b-6496f50e4713
Content-Type: application/json
Authorization: Bearer {{token}}
###
PUT {{host}}/api/exercises/7d0b720b-73ab-4a61-b43b-6496f50e4713
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "push"
}
###
DELETE {{host}}/api/exercises/9b19c037-5865-4444-8491-5d3246be656d
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST {{host}}/api/progression_rules
Content-Type: application/json
###
DELETE {{host}}/api/progression_rules
Content-Type: application/json
###
GET {{host}}/api/progression_rules
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST {{host}}/api/workouts
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "started_at": "2026-04-08T16:30:00Z",
    "ended_at": "2026-04-08T16:40:00Z",
    "volume": 0,
    "prs": 0
}
###
GET {{host}}/api/workouts
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/api/workouts/e425c89a-f7d8-432b-992f-a58afd9673f3
Content-Type: application/json
Authorization: Bearer {{token}}
###
DELETE {{host}}/api/workouts/f74797af-e1cf-412a-a2e5-6263c6262272
Content-Type: application/json
Authorization: Bearer {{token}}
###
POST {{host}}/api/workouts/e425c89a-f7d8-432b-992f-a58afd9673f3/sets
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
	"exercise_id": "7d0b720b-73ab-4a61-b43b-6496f50e4713",
	"progress_track": "a2658d67-d266-461b-95c1-7e8769079a2a",
	"weight_in_lbs": 245,
	"reps": 3,
	"time_in_seconds": 0
	
}
###
POST {{host}}/api/workouts/{{workout_id}}/sets/batch
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "sets": [
        {
        
        "exercise_id": {{exercise_id_a}},
        "progress_track": {{prog_track}},
        "weight_in_lbs": 250,
        "reps": 5,
        "time_in_seconds": 0
        
        },
        {
        
        "exercise_id": {{exercise_id_b}},
        "progress_track": {{prog_track}},
        "weight_in_lbs": 250,
        "reps": 8,
        "time_in_seconds": 0
        
        }
    ]
}

###
GET {{host}}/api/workouts/{{workout_id}}/sets
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/api/sets/5e764b8b-f371-4d6b-806f-325de6392372
Content-Type: application/json
Authorization: Bearer {{token}}
###
PUT {{host}}/api/sets/6d8af7b1-76fc-4562-ae75-30c1bffb8206
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "exercise_id": "0bb93ab5-8b3a-46e5-a9db-1a34213d5f71",
    "progress_track": "a2658d67-d266-461b-95c1-7e8769079a2a",
    "weight_in_lbs": 185,
    "reps": 12,
    "time_in_seconds": 0
}
###
DELETE {{host}}/api/sets/5e764b8b-f371-4d6b-806f-325de6392372
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/api/exercises/{{exercise_id_b}}/1rm
Content-Type: application/json
Authorization: Bearer {{token}}
###
GET {{host}}/api/exercises/{{exercise_id_b}}/volume
Content-Type: application/json
Authorization: Bearer {{token}}
