POST http://localhost:8080/api/users/register
Content-Type: application/json

{
    "email": "gamvred7@gmail.com",
    "username": "gabeamv",
    "password": "password123"
}
###
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "username": "gabeamv",
    "password": "password123"
}
###
DELETE http://localhost:8080/admin/reset
###
POST http://localhost:8080/api/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvdmVybG9hZGVkIiwic3ViIjoiZTMzZGY4YzMtZWViNS00MTg3LThlNTktYjc2MjY0NjA0ZTY3IiwiZXhwIjoxNzc1MDI2NTA3LCJpYXQiOjE3NzUwMjI5MDd9.ZzkfV_uMFBCrGwNDP8VhujaP4k7M2X15JEIQ8PQ4jBM

{
    "name": "pushups",
    "is_custom": true
}
###
GET http://localhost:8080/api/exercises
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvdmVybG9hZGVkIiwic3ViIjoiZTMzZGY4YzMtZWViNS00MTg3LThlNTktYjc2MjY0NjA0ZTY3IiwiZXhwIjoxNzc1MDI2NTA3LCJpYXQiOjE3NzUwMjI5MDd9.ZzkfV_uMFBCrGwNDP8VhujaP4k7M2X15JEIQ8PQ4jBM
